services:

  postgres:
    image: postgres:16
    container_name: resume_matcher_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume_matcher

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d resume_matcher"]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: resume_matcher_api

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/resume_matcher

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped


volumes:
  postgres_data: